name: Deploy Estatico UFSJ

on:
  push:
    branches:
      - main # Branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Pegando os arquivos do repositório
        uses: actions/checkout@v4

      - name: 🚀 Enviando via SFTP
        uses: wangyucode/sftp-upload-action@v3
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PWD }}
          port: 32001
          localDir: './'
          remoteDir: '/upload/'
          exclude: '.git,.github,README.md' # Arquivos que serão ignorados no upload
          # Força a criação da pasta remota caso ela não exista por algum motivo
          forceUpload: true