name: Deploy Estatico UFSJ

on:
  push:
    branches:
      - main # Branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Pegando os arquivos do repositório
        uses: actions/checkout@v4

      - name: 🚀 Enviando via SFTP
        uses: pressidium/sftp-upload@v1.1.0
        with:
          host: ${{ secrets.SFTP_HOST }}
          user: ${{ secrets.SFTP_USER }}
          pass: ${{ secrets.SFTP_PWD }}
          port: 32001
          src: ./        # Pasta local (raiz do projeto)
          dest: /upload/ # Pasta no servidor
          exclude: ".git* .github* README.md" # Arquivos que NÃO vão para o servidor